"""Search for a witness inside an arbitrary permutation-group symmetry class.

WHY THIS FILE EXISTS.  `cyclic.py` hard-codes one ansatz (Z_n) and `extend.py`
hard-codes one more (Z_n plus fixed points).  Both were dead ends at 35 points:
Z_35 is excluded outright by `obstruction.py`, and the Z_33+e rungs each ran to
a 30-minute cap without a verdict.  This file takes the group as *data* -- a
list of generators as permutations of the point set -- so any of the 45 groups
in `groups.json` can be tried without new code.

THE ENCODING.  One Boolean per orbit of the group on the k-subsets.  A colouring
constant on orbits is exactly a G-invariant colouring.  For each s-subset W the
faces of W meet some SET S of orbits; W is monochromatic-0 iff every variable in
S is 0, so the constraint is the clause `OR_{i in S} x_i` (and dually the
all-negative clause).  Two different s-sets that meet the same set of orbits
give the *same* pair of clauses, so the CNF is deduplicated on S.

THAT DEDUPLICATION IS THE POINT.  There are always C(35,5) = 324,632 five-sets,
but under a large group they collapse onto very few distinct orbit-sets: the
order-1344 group AGL(3,2) has 101 variables, and no clause can mention more
than 5 of them, so at most C(101,5) distinct clauses exist and in practice far
fewer.  A bigger group is a smaller instance.

SOUNDNESS DOES NOT DEPEND ON THE GROUP.  Nothing here assumes the group is a
5'-group, and nothing needs |G| -- which matters, because two of the groups in
the tower have order ~10^15 and cannot be enumerated.  Orbits are computed by
BFS under the generators alone.  If the class happens to be empty (some s-set
has all its faces in ONE orbit, so the CNF holds both x_i and ~x_i) the solver
returns UNSAT at once, which is the correct answer, merely uninformative.  A
5'-group is what makes UNSAT *interesting* rather than predetermined.

WHAT A RESULT MEANS.  SAT, once verified on the full C(n,k)-bit colouring, is a
witness and a genuine lower bound.  UNSAT is a null *for that symmetry class
only*: it says no G-invariant witness exists, never that no witness exists.
"""

from __future__ import annotations

import argparse
import json

import contracts
import sys
import time
from itertools import combinations
from math import comb

import brute
from capped import run_capped_out_of_process


def face_orbits(gens, n, k=4):
    """Orbits of the group generated by `gens` on the k-subsets of range(n).

    BFS from each unvisited face under the generators.  The group itself is
    never enumerated, so this is linear in C(n,k) * len(gens) regardless of |G|.
    Returns (orbit_of: face -> orbit id, sizes: list of orbit sizes).
    """
    for g in gens:
        if len(g) != n or sorted(g) != list(range(n)):
            raise ValueError(f"generator is not a permutation of {n} points: {g!r}")

    faces = list(combinations(range(n), k))
    orbit_of = {}
    sizes = []
    for f in faces:
        if f in orbit_of:
            continue
        oid = len(sizes)
        stack = [f]
        orbit_of[f] = oid
        count = 0
        while stack:
            cur = stack.pop()
            count += 1
            for g in gens:
                img = tuple(sorted(g[v] for v in cur))
                if img not in orbit_of:
                    orbit_of[img] = oid
                    stack.append(img)
        sizes.append(count)
    assert sum(sizes) == len(faces), (sum(sizes), len(faces))
    return orbit_of, sizes


def distinct_orbit_sets(orbit_of, n, size, k, translations=False):
    """The distinct sets of orbits met by the k-faces of a `size`-subset.

    Those sets ARE the clauses: two subsets meeting the same orbits give the
    same constraint. The slow path walks all C(n,size) subsets.

    FAST PATH. If the group contains every translation x -> x+c on all n points,
    then every subset W translates to W - w, which contains 0 and meets exactly
    the same orbits (translation permutes faces within their orbits). So walking
    only the subsets that contain 0 -- C(n-1,size-1) of them -- reaches every
    orbit-set. At R(5,5;3) on 88 points that is 2,225,895 instead of 39,175,752,
    a factor of 17.6, which is the difference between a feasible cell and an
    infeasible one.

    The precondition is checked by the caller with
    `grouporder.has_all_translations`, never assumed: a group with fixed points
    does not have it, and using the fast path there would silently drop clauses.
    """
    seen = set()
    if translations:
        walked = 0
        for rest in combinations(range(1, n), size - 1):
            walked += 1
            W = (0,) + rest
            seen.add(frozenset(orbit_of[f] for f in combinations(W, k)))
        assert walked == comb(n - 1, size - 1), (walked, comb(n - 1, size - 1))
    else:
        walked = 0
        for W in combinations(range(n), size):
            walked += 1
            seen.add(frozenset(orbit_of[f] for f in combinations(W, k)))
        assert walked == comb(n, size), (walked, comb(n, size))
    return seen


def build_cnf(gens, n=35, s=5, t=5, k=4):
    """CNF over one variable per k-face orbit.  Returns (clauses, orbit_of, stats)."""
    orbit_of, sizes = face_orbits(gens, n, k)
    n_vars = len(sizes)

    # Distinct orbit-sets, one for each clique size.  Variables are 1-based.
    # The translation shortcut, when the group really has it. Checked via
    # Schreier-Sims membership, never assumed -- a group with fixed points does
    # not have it and the shortcut would then silently drop clauses.
    from grouporder import has_all_translations
    fast = has_all_translations(gens, n)

    def orbit_sets(size):
        # distinct_orbit_sets carries the completeness assert: it checks what it
        # actually walked, not what the formula says it should have, so a
        # premature exit cannot hide behind a correct-looking clique count.
        return {frozenset(i + 1 for i in S)
                for S in distinct_orbit_sets(orbit_of, n, size, k,
                                             translations=fast)}

    pos_sets = orbit_sets(s)
    neg_sets = orbit_sets(t) if t != s else pos_sets

    clauses = [sorted(S) for S in pos_sets]
    clauses += [sorted(-v for v in S) for S in neg_sets]

    # A singleton orbit-set is a unit clause. Two different things can happen,
    # and conflating them was a real defect: on the DIAGONAL (s == t) the two
    # clause families are built from the SAME sets, so a singleton {v} emits
    # both [v] and [-v] and the class is empty by construction. OFF the
    # diagonal they are different families, and a singleton in pos_sets alone
    # is only a unit clause -- it fixes one orbit's colour and proves nothing.
    # `forced_mono_vars` reports the units; `contradictory_vars` reports the
    # ones that really are forced both ways, and only that justifies the word
    # "empty".
    pos_singletons = {next(iter(S)) for S in pos_sets if len(S) == 1}
    neg_singletons = {next(iter(S)) for S in neg_sets if len(S) == 1}
    singletons = sorted(pos_singletons)
    contradictory = sorted(pos_singletons & neg_singletons)
    stats = {
        "n": n, "vars": n_vars, "clauses": len(clauses),
        "distinct_pos": len(pos_sets), "distinct_neg": len(neg_sets),
        "cliques_s": comb(n, s), "cliques_t": comb(n, t),
        "collapse": round(comb(n, s) / max(len(pos_sets), 1), 1),
        "forced_mono_vars": singletons,
        "contradictory_vars": contradictory,
        "translation_fast_path": fast,
        "orbit_sizes": {"min": min(sizes), "max": max(sizes)},
    }
    return clauses, orbit_of, stats


def expand(model, orbit_of, n, k=4):
    """Expand an orbit model to the full C(n,k)-bit colouring, lex face order."""
    assign = {}
    for lit in model or []:
        assign[abs(lit)] = 1 if lit > 0 else 0
    return [assign.get(orbit_of[f] + 1, 0) for f in combinations(range(n), k)]


def is_invariant(chi, gens, n, k=4):
    """Cross-check: the expanded colouring really is constant on orbits."""
    index = {f: i for i, f in enumerate(combinations(range(n), k))}
    for g in gens:
        for f, i in index.items():
            if chi[index[tuple(sorted(g[v] for v in f))]] != chi[i]:
                return False
    return True


def run(name, gens, n=35, s=5, t=5, k=4, cap_s=600.0, verbose=True):
    # A finite cap has to be enforced by something that does not need the
    # solver's cooperation. solve_with_deadline() now REFUSES a cap it cannot
    # keep rather than silently running unbounded, so route the request to the
    # child-process deadline instead of handing the caller an error. The child
    # is invoked with cap_s=None by run_capped_out_of_process, so this does not
    # recurse.
    if cap_s is not None:
        from capped import run_capped_out_of_process
        _kw = dict({"name": name, "gens": gens, "n": n, "s": s, "t": t, "k": k, "verbose": verbose})
        capped = run_capped_out_of_process(run, _kw, cap_s)
        if capped.status == "TIMEOUT":
            return {"name": name, "status": "TIMEOUT",
                    "solve_s": round(capped.elapsed_s, 2), "cap_s": cap_s,
                    "chi": None, "vars": None, "clauses": None}
        if capped.status == "ERROR":
            raise RuntimeError(f"{name}: capped child failed: {capped.detail}")
        return capped.value

    from pysat.formula import CNF
    from pysat.solvers import Cadical195

    from capped import solve_with_deadline

    t0 = time.time()
    clauses, orbit_of, stats = build_cnf(gens, n, s, t, k)
    build_s = time.time() - t0
    if verbose:
        print(f"  {name}: {stats['vars']} vars, {stats['clauses']} clauses "
              f"({stats['collapse']}x collapse from {stats['cliques_s']} cliques), "
              f"built {build_s:.1f}s", flush=True)
        if stats["contradictory_vars"]:
            print(f"    NOTE: {len(stats['contradictory_vars'])} orbit(s) are forced "
                  f"both ways -- this class is empty by construction, expect UNSAT",
                  flush=True)
        elif stats["forced_mono_vars"]:
            print(f"    NOTE: {len(stats['forced_mono_vars'])} orbit(s) carry a unit "
                  f"clause -- a constraint, NOT a proof that the class is empty",
                  flush=True)

    cnf = CNF()
    for c in clauses:
        cnf.append(c)
    t1 = time.time()
    with Cadical195(bootstrap_with=cnf) as solver:
        status, model = solve_with_deadline(solver, cap_s)
    solve_s = time.time() - t1

    # Small instances get decided a second time, by enumeration, with no
    # solver involved. This is the check that separates "CDCL is struggling
    # because the problem is hard" from "CDCL is being handed the wrong
    # problem" -- four ladder rungs timed out where the arithmetic said they
    # should not have, and two cap defects have already shipped on this path.
    if stats["vars"] <= brute.MAX_VARS:
        t2 = time.time()
        b_status, b_model = brute.decide(clauses, stats["vars"])
        rec_brute = {"status": b_status, "s": round(time.time() - t2, 3),
                     "models": brute.count_models(clauses, stats["vars"])}
        if b_status != status:
            raise AssertionError(
                f"{name}: brute force says {b_status} but CaDiCaL says "
                f"{status} on {stats['vars']} vars / {len(clauses)} clauses. "
                f"One of them is wrong and neither result may be used.")
        if b_status == "SAT" and not brute.satisfies(clauses, b_model):
            raise AssertionError(f"{name}: brute-force model does not satisfy")
        if verbose:
            print(f"    cross-check: brute force over 2^{stats['vars']} "
                  f"colourings agrees ({b_status}, {rec_brute['s']}s, "
                  f"{rec_brute['models']} surviving colourings)", flush=True)
    else:
        rec_brute = None

    rec = {"name": name, "status": status, "solve_s": round(solve_s, 2),
           "build_s": round(build_s, 2), "cap_s": cap_s, "chi": None,
           "brute": rec_brute, **stats}

    if status == "SAT":
        from verify import verify_both, verify_lex
        chi = expand(model, orbit_of, n, k)
        if not is_invariant(chi, gens, n, k):
            raise AssertionError(f"{name}: expanded colouring is not G-invariant")
        if not verify_both(n, s, t, k, chi):
            raise AssertionError(
                f"{name}: model is NOT a witness at n={n}: "
                f"{verify_lex(n, s, t, k, chi)!r}")
        rec["chi"] = chi
        if verbose:
            print(f"    WITNESS at n={n} in {solve_s:.1f}s, verified on the full "
                  f"{comb(n, k)}-bit colouring => R({s},{t};{k}) >= {n+1}", flush=True)
    elif verbose:
        # Built lazily on purpose: a dict literal evaluates BOTH branches, and
        # the TIMEOUT one formats cap_s, which run_capped_out_of_process sets
        # to None because the deadline is enforced by the OS instead. That
        # crashed every UNSAT before it could be recorded.
        if status == "UNSAT":
            word = f"no {name}-invariant witness at n={n} (a null for THIS class only)"
        else:
            budget = "the outer process cap" if cap_s is None else f"cap {cap_s:.0f}s"
            word = f"TIMEOUT at {budget} -- a null under this budget, not a verdict"
        print(f"    {word} ({solve_s:.1f}s)", flush=True)
    return rec



def _gens_fingerprint(gens):
    """SHA-256 of the generator list, canonically encoded.

    The problem key below records n, s, t, k -- the QUESTION. This records the
    GROUP. Both are needed. Matching a cached row by group name alone lets a
    run at different Ramsey parameters reuse it, and matching by parameters
    alone is no better: a group's name is a label a human chose, and the same
    label can be attached to a different generator list.

    The FULL 64-character digest, not a prefix. The docstring says SHA-256 and
    a truncation would make that false; the rows that carry this value are the
    binding between a claim and the group it is about.
    """
    import hashlib
    canon = json.dumps([list(map(int, g)) for g in gens], separators=(",", ":"))
    return hashlib.sha256(canon.encode()).hexdigest()


# Public names. `certify_nulls.py` and `crosscheck_n63.py` report on "the five
# deposited classes", and without these they would report on five *names* --
# a weaker statement than their labels make. One implementation, so the
# binding cannot drift between the programs that use it.
gens_fingerprint = _gens_fingerprint


def refuse_ambiguous_names(groups, path):
    """Return {name: gens_sha}, or exit 2 if a name is not injective here.

    A gate that says "all five classes" and keys on the name is only as strong
    as the assumption that the names distinguish the groups. `_resume` refuses
    the same input for the same reason; anything binding rows by name must
    refuse it too, or it can check one class twice and never check another.
    """
    seen = {}
    for g in groups:
        sha = _gens_fingerprint(g["generators"])
        if g["name"] in seen and seen[g["name"]] != sha:
            sys.stderr.write(
                f"{path}: two groups are both named {g['name']!r} with "
                f"different generators. Rename one; a per-class claim cannot "
                f"be resolved by name here.\n")
            raise SystemExit(2)
        seen[g["name"]] = sha
    return seen


def _problem_key(**kw):
    """Canonical identity of the instance a cached row belongs to."""
    return {k: (list(v) if isinstance(v, (list, tuple)) else v)
            for k, v in sorted(kw.items())}


# The identity contracts live in contracts.py, owned once. These names stay so
# existing callers keep working; they are aliases, not a second definition.
problem_identity = contracts.problem_identity
row_problem_identity = contracts.row_problem_identity


def _resume(results, problem, groups, path):
    """Delegates to contracts.resume -- see there. Both engines share one body
    so that their resume semantics cannot differ."""
    return contracts.resume(results, problem, groups, path, _gens_fingerprint)

def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--groups", default="groups.json", help="JSON list of groups")
    ap.add_argument("--name", action="append", help="run only these (repeatable)")
    ap.add_argument("--max-vars", type=int, default=10**9)
    ap.add_argument("--n", type=int, default=35)
    ap.add_argument("--s", type=int, default=5, help="clique size to avoid in colour 0")
    ap.add_argument("--t", type=int, default=5, help="clique size to avoid in colour 1")
    ap.add_argument("--k", type=int, default=4, help="uniformity: we colour k-subsets")
    ap.add_argument("--cap", type=float, default=600.0)
    ap.add_argument("--out", default="ansatz_results.json")
    a = ap.parse_args()

    with open(a.groups) as f:
        groups = json.load(f)
    # groups.json caches orbit counts for k=4 only; for any other uniformity
    # the cached number is the wrong quantity, so fall through to no filter
    # rather than silently filtering on a number that does not apply.
    key = f"orbit_count_{a.k}subsets"
    # A MISSING count is not a small one. `g.get(key, 0) <= max_vars` read an
    # absent field as zero, so a class whose size was never measured passed
    # the cap as though it were the smallest possible -- the filter reported
    # a class as under the cap on no evidence at all. An unmeasured class is
    # measured here rather than assumed.
    def _size(g):
        v = g.get(key)
        if v is None:
            v = len(face_orbits(g["generators"], a.n, k=a.k)[1])
            g[key] = v
        return v
    todo = [g for g in groups
            if (not a.name or g["name"] in a.name)
            and _size(g) <= a.max_vars]
    todo.sort(key=_size)
    print(f"{len(todo)} group(s), cap {a.cap:.0f}s each", flush=True)

    try:                       # append, so one-group-per-invocation accumulates
        with open(a.out) as f:
            results = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        results = []
    problem = _problem_key(n=a.n, s=a.s, t=a.t, k=a.k)
    done = _resume(results, problem, todo, a.out)
    todo = [g for g in todo
            if (g["name"], _gens_fingerprint(g["generators"])) not in done]
    print(f"  ({len(done)} already decided in {a.out} at {problem}, "
          f"skipping those)", flush=True)

    for g in todo:
        # The cap is enforced by the OS, not by the solver: Cadical195.interrupt()
        # raises NotImplementedError under python-sat >= 1.9.dev15, so an
        # in-process deadline is a silent no-op (see capped.py).
        capped = run_capped_out_of_process(
            run, {"name": g["name"], "gens": g["generators"], "n": a.n,
                  "s": a.s, "t": a.t, "k": a.k, "verbose": True}, a.cap)
        if capped.status == "TIMEOUT":
            print(f"  {g['name']}: TIMEOUT after {capped.elapsed_s:.1f}s "
                  f"(cap {a.cap:.0f}s) [outer process cap] -- a null under this "
                  f"budget, not a verdict.", flush=True)
            # The count for THIS problem's uniformity. This path hardcoded
            # orbit_count_4subsets whatever k was, so a triple problem
            # recorded the quadruple-orbit count: the shipped C_34 row of the
            # (4,5;3) sweep says 1544 variables, which is the k = 4 count --
            # the k = 3 count is 193. A field measured for another uniformity
            # is a wrong datum, not a missing one, so when the matching field
            # is absent the size is recorded as unknown rather than borrowed.
            rec = {"name": g["name"], "status": "TIMEOUT",
                   "solve_s": round(capped.elapsed_s, 2), "cap_s": a.cap,
                   "vars": g.get(f"orbit_count_{a.k}subsets"),
                   "vars_field": f"orbit_count_{a.k}subsets",
                   "clauses": None, "chi": None}
        elif capped.status == "ERROR":
            raise RuntimeError(f"ansatz.run child failed on {g['name']}: "
                               f"{capped.detail}")
        else:
            rec = capped.value
        rec["order"] = g.get("order")
        row = {kk: vv for kk, vv in rec.items() if kk != "chi"}
        row["problem"] = problem
        row["gens_sha"] = _gens_fingerprint(g["generators"])
        results.append(row)
        with open(a.out, "w") as f:
            json.dump(results, f, indent=1)
        if rec["status"] == "SAT":
            # Plain witness_n<N>.json: independent_check.py takes explicit
            # paths and the group name can contain '|' and '/'.
            tag = "" if (a.s, a.t, a.k) == (5, 5, 4) else f"_{a.s}{a.t}_{a.k}"
            fn = f"witness{tag}_n{a.n}.json"
            with open(fn, "w") as f:
                json.dump({"n": a.n, "s": a.s, "t": a.t, "k": a.k,
                           "ansatz": g["name"], "order": g.get("order"),
                           "certifies": f"R({a.s},{a.t};{a.k}) >= {a.n+1}",
                           "chi": rec["chi"]}, f)
            print(f"    witness written to {fn}", flush=True)

    print(json.dumps([{kk: vv for kk, vv in r.items()
                       if kk in ("name", "vars", "clauses", "status", "solve_s")}
                      for r in results], indent=1))
    sat = [r["name"] for r in results if r.get("status") == "SAT"]
    if sat:
        print(f"\n*** SAT: {sat} ***", flush=True)


if __name__ == "__main__":
    main()
