"""Measured cost calibration for the R(s,t;k) witness search.

Two rules this file is written to obey:

  - Back-test the model against ground truth already held, before quoting any
    projection. Ground truth here is the completed R(4,4;3) bracket.
  - Quote the scaling law with the number. A headline figure without its growth
    exponent underestimated one range in this repo by ~2600x.
  - Calibrate with REPEATS; publish the spread; discard contaminated points.
    Where spread exceeds the effect, the figure is a LOWER BOUND -- say so.
  - Never apply an unmeasured speedup. Compute rather than eyeball.

Spread is generated by relabelling vertices with a random permutation before
building the CNF. That yields isomorphic instances -- same answer, same size,
genuinely different clause and variable order -- so the spread measured is the
solver's real sensitivity, not noise from a different problem.

Each instance runs in its own process with a hard wall-clock cap, so a hang
costs the cap and not the run.
"""

from __future__ import annotations

import argparse
import json
import sys
import multiprocessing as mp
import platform
import random
import statistics
import time
from itertools import combinations
from math import comb

from pysat.formula import CNF
from pysat.solvers import Cadical195

from capped import run_in_child
from verify import verify_both


def build_cnf_permuted(n, s, t, k, seed):
    """CNF for (n,s,t,k) with vertices relabelled by a seeded permutation.

    Isomorphic to the unpermuted instance: same variable count, same clause
    count, same satisfiability. Only the ordering differs, which is exactly the
    axis a CDCL solver is sensitive to.
    """
    rng = random.Random(seed)
    perm = list(range(n))
    rng.shuffle(perm)
    index = {sub: i + 1 for i, sub in enumerate(combinations(range(n), k))}

    def rank_of(vertices):
        return index[tuple(sorted(perm[v] for v in vertices))]

    cnf = CNF()
    for clique in combinations(range(n), s):
        cnf.append([rank_of(sub) for sub in combinations(clique, k)])
    for clique in combinations(range(n), t):
        cnf.append([-rank_of(sub) for sub in combinations(clique, k)])
    assert len(cnf.clauses) == comb(n, s) + comb(n, t)
    return cnf, perm, index


def _run_one_returning(n, s, t, k, seed):
    """The work of one calibration point, returning its record.

    Split out of `_run_one` so the supervisor in `capped.run_in_child` owns the
    queue: a child that raises now reports ERROR through the supervisor instead
    of exiting silently and hanging the parent on an unbounded `q.get()`.
    """
    t0 = time.time()
    cnf, perm, index = build_cnf_permuted(n, s, t, k, seed)
    build_s = time.time() - t0
    t1 = time.time()
    with Cadical195(bootstrap_with=cnf) as solver:
        sat = solver.solve()
        model = solver.get_model() if sat else None
    solve_s = time.time() - t1

    verified = None
    if sat:
        nv = comb(n, k)
        chi_perm = [0] * nv
        for lit in model:
            v = abs(lit)
            if 1 <= v <= nv:
                chi_perm[v - 1] = 1 if lit > 0 else 0
        # The model is in permuted coordinates; the verifier re-derives the
        # property directly on them, which is valid because a relabelling of
        # vertices maps witnesses to witnesses.
        verified = verify_both(n, s, t, k, chi_perm)
    return {
        "n": n, "s": s, "t": t, "k": k, "seed": seed,
        "status": "SAT" if sat else "UNSAT",
        "build_s": build_s, "solve_s": solve_s,
        "vars": comb(n, k), "clauses": comb(n, s) + comb(n, t),
        "verified": verified,
    }


def _run_one(n, s, t, k, seed, q):
    t0 = time.time()
    cnf, perm, index = build_cnf_permuted(n, s, t, k, seed)
    build_s = time.time() - t0
    t1 = time.time()
    with Cadical195(bootstrap_with=cnf) as solver:
        sat = solver.solve()
        model = solver.get_model() if sat else None
    solve_s = time.time() - t1

    verified = None
    if sat:
        nv = comb(n, k)
        chi_perm = [0] * nv
        for lit in model:
            v = abs(lit)
            if 1 <= v <= nv:
                chi_perm[v - 1] = 1 if lit > 0 else 0
        # The model is in permuted coordinates; the verifier re-derives the
        # property directly on them, which is valid because a relabelling of
        # vertices maps witnesses to witnesses.
        verified = verify_both(n, s, t, k, chi_perm)
    q.put(
        {
            "n": n, "s": s, "t": t, "k": k, "seed": seed,
            "status": "SAT" if sat else "UNSAT",
            "build_s": build_s, "solve_s": solve_s,
            "vars": comb(n, k), "clauses": comb(n, s) + comb(n, t),
            "verified": verified,
        }
    )


def timed_run(n, s, t, k, seed, cap_s):
    """One instance under an enforced end-to-end cap.

    Status is one of SAT / UNSAT / TIMEOUT / ERROR. The cap covers build +
    solve + verify, so a TIMEOUT bounds the WHOLE call and `solve_s` is left
    None rather than being imputed as `cap_s`: a run can time out during
    construction or verification, and recording the cap as a solver time
    manufactures a measurement that was never taken.
    """
    skeleton = {
        "n": n, "s": s, "t": t, "k": k, "seed": seed,
        "vars": comb(n, k), "clauses": comb(n, s) + comb(n, t),
    }
    res = run_in_child(_run_one_returning, {"n": n, "s": s, "t": t, "k": k,
                                            "seed": seed}, cap_s)
    if res.status == "TIMEOUT":
        return {**skeleton, "status": "TIMEOUT", "solve_s": None,
                "build_s": None, "verified": None, "capped": True,
                "cap_s": cap_s, "wall_s": res.elapsed_s, "censored": True,
                "detail": res.detail}
    if res.status == "ERROR":
        return {**skeleton, "status": "ERROR", "solve_s": None,
                "build_s": None, "verified": None, "capped": False,
                "cap_s": cap_s, "wall_s": res.elapsed_s, "censored": False,
                "detail": res.detail}
    rec = res.value
    rec["wall_s"] = res.elapsed_s
    rec["capped"] = False
    rec["censored"] = False
    rec["cap_s"] = cap_s
    return rec


def ladder(family, ns, repeats, cap_s, out):
    s, t, k = family
    rows = []
    for n in ns:
        times, statuses = [], []
        for r in range(repeats):
            rec = timed_run(n, s, t, k, seed=1000 + r, cap_s=cap_s)
            rows.append(rec)
            times.append(rec["solve_s"])
            statuses.append(rec["status"])
            if rec.get("verified") is False:
                raise AssertionError(f"UNVERIFIED MODEL at n={n} seed={rec['seed']}")
            if rec["solve_s"] is None:
                # Censored or failed: report the wall-clock bound, never a
                # solver time we did not observe.
                shown = f">{rec['wall_s']:7.2f}s"
            else:
                shown = f"{rec['solve_s']:8.2f}s"
            print(
                f"  ({s},{t};{k}) n={n:>2} rep{r}: {rec['status']:>7} "
                f"{shown}  vars={rec['vars']:>6} "
                f"clauses={rec['clauses']:>8}"
                + ("  [VERIFIED]" if rec.get("verified") else "")
                + (f"  [{rec['detail']}]" if rec.get("detail") else ""),
                flush=True,
            )
        # NO break on the first timeout. Stopping the repeats there left ONE
        # censored observation, whose imputed cap value was then summarised as
        # a median with spread 1.0 -- statistics of a substituted constant, not
        # of measured solving. SAT runtime is not monotone across permutations
        # either, so one timeout does not settle the rung.
        finished = [x for x in times if x is not None]
        n_censored = sum(1 for st in statuses if st == "TIMEOUT")
        n_error = sum(1 for st in statuses if st == "ERROR")
        rows_summary = {
            "n": n, "family": f"({s},{t};{k})",
            "status": statuses[0] if len(set(statuses)) == 1 else statuses,
            "reps": len(statuses), "completed": len(finished),
            "censored": n_censored, "errors": n_error, "cap_s": cap_s,
            "vars": comb(n, k), "clauses": comb(n, s) + comb(n, t),
        }
        # Repeats at one rung are permutations of the same instance, so they
        # are isomorphic and MUST agree. A rung that answered both SAT and
        # UNSAT is reporting a solver or encoding defect, and a median over
        # whichever repeats finished would be a statistic about a broken run.
        decided = {st for st in statuses if st in ("SAT", "UNSAT")}
        contradictory = len(decided) > 1
        invalid = bool(n_error) or contradictory
        if invalid:
            # An ERROR or a self-contradiction dominates every other branch, including a rung where
            # some repeats DID finish: a median over the survivors of a run
            # that was partly broken is a statistic about which repeats
            # happened to work.
            rows_summary.update({
                "min_s": None, "max_s": None, "median_s": None,
                "spread_x": None, "lower_bound_s": None,
                "invalid": True,
                "note": (f"{n_error}/{len(statuses)} repeats ERRORED"
                         + (f"; repeats disagree {sorted(decided)} on an "
                            f"isomorphic instance" if contradictory else "")
                         + "; this rung measures nothing and is not a bound"),
            })
        elif finished:
            lo, hi = min(finished), max(finished)
            rows_summary.update({
                "min_s": lo, "max_s": hi,
                "median_s": statistics.median(finished),
                "spread_x": (hi / lo) if lo > 0 else None,
            })
        else:
            # Every repeat censored by the CAP, none errored: the only
            # defensible statement is a bound.
            rows_summary.update({
                "min_s": None, "max_s": None, "median_s": None,
                "spread_x": None, "lower_bound_s": cap_s,
            })
        if n_censored and not invalid:
            rows_summary["note"] = (
                f"{n_censored}/{len(statuses)} repeats censored at {cap_s}s; "
                f"any median below is over COMPLETED runs only"
            )
        if invalid:
            print(
                f"    -> n={n}: INVALID ({n_error} ERRORED"
                + (f", repeats disagree {sorted(decided)}" if contradictory else "")
                + "). This rung measures nothing and is NOT a bound.",
                flush=True,
            )
        elif finished:
            print(
                f"    -> n={n}: median {rows_summary['median_s']:.2f}s over "
                f"{len(finished)}/{len(statuses)} completed, spread "
                f"{rows_summary['min_s']:.2f}-{rows_summary['max_s']:.2f}s"
                + (f", {n_censored} censored at {cap_s}s" if n_censored else ""),
                flush=True,
            )
        else:
            print(
                f"    -> n={n}: ALL {len(statuses)} repeats censored at "
                f"{cap_s}s. Runtime is a LOWER BOUND of >{cap_s}s; no median, "
                f"no spread.",
                flush=True,
            )
        out["summary"].append(rows_summary)
        if all(st == "TIMEOUT" for st in statuses):
            # Only stop when the rung told us nothing at all. A rung with SOME
            # completed repeats is still a measurement, and runtime is not
            # monotone in n (n=32 solved faster than n=31), so a single slow
            # permutation is not grounds to abandon the ladder.
            print(f"    -> every repeat censored at n={n}; stopping this ladder.",
                  flush=True)
            break
    out["raw"].extend(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cap", type=float, default=300.0, help="per-instance cap (s)")
    ap.add_argument("--repeats", type=int, default=3)
    ap.add_argument("--out", default="calibration.json")
    ap.add_argument("--family", default="554", choices=["554", "443", "both"])
    args = ap.parse_args()

    out = {
        "host": {
            "machine": platform.machine(),
            "python": platform.python_version(),
            "note": "shared cloud container; a concurrent job may be running",
        },
        "cap_s": args.cap, "repeats": args.repeats,
        "summary": [], "raw": [],
    }

    if args.family in ("443", "both"):
        print("Ladder A -- R(4,4;3), the back-test bracket (published value 13):")
        ladder((4, 4, 3), list(range(8, 14)), args.repeats, args.cap, out)

    if args.family in ("554", "both"):
        print("\nLadder B -- R(5,5;4), the target family (SAT side):")
        ladder(
            (5, 5, 4),
            [10, 14, 18, 22, 26, 29, 31, 33, 34, 35],
            args.repeats, args.cap, out,
        )

    with open(args.out, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nwrote {args.out}")

    # A calibration that contains a rung which measured nothing is not a
    # calibration. Saying so in the JSON and exiting 0 leaves it to a caller to
    # notice, and the caller here is a shell script that reads exit status.
    bad = [r for r in out["summary"] if r.get("invalid")]
    if bad:
        print(f"\n{len(bad)} rung(s) measured nothing (repeats ERRORED); this "
              f"calibration is not usable:", file=sys.stderr)
        for r in bad:
            print(f"  n={r['n']} {r['family']}: {r.get('note')}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
