import sys
"""The R(4,6;3) >= 64 construction, stated as mathematics rather than output.

Companion to `construction.py`, which does the same for the 83-point
`R(4,4,4;3)` object. The witness file holds 39,711 bits; the object is 120
numbers.

THE CONSTRUCTION. Let H be the subgroup of Z_63^* generated by
{10, 19, 37, 46, 55}, of order 6, and let

    G = { x -> u*x + b : u in H, b in Z_63 },   |G| = 378.

G acts on the C(63,3) = 39,711 triples of Z_63 with exactly 120 orbits. Unlike
the 83-point case the action is NOT free: its orbit sizes are 378, 189, 126,
63 and 21. The short orbits arise from nontrivial setwise stabilisers in the
full affine group, which need not consist of pure multipliers. The displayed
orbit-colour assignment gives colour-class sizes 14,070 and 25,641; these
sizes are properties of this assignment, not consequences of nonfreeness
alone. Regularity only forces each class to be a multiple of the orbit size,
and enumerating all invariant good colourings of that class gives 36, of which
twenty-four are unbalanced. See `construction.py`, which states the same
correction.

TABLE below maps each orbit representative to its colour. Colour 0 avoids
K_4^(3); colour 1 avoids K_6^(3).

THEOREM. No 4-subset of Z_63 has all four triples colour 0, and no 6-subset has
all twenty triples colour 1. Hence R(4,6;3) >= 64.
"""

N = 63

# The multiplier subgroup H <= Z_63^*, closed under multiplication mod 63.
SUBGROUP = [1, 10, 19, 37, 46, 55]

# Orbit representative -> colour. The whole construction.
TABLE = {
    (0, 1, 2): 1,  (0, 1, 3): 0,  (0, 1, 4): 1,
    (0, 1, 5): 1,  (0, 1, 6): 1,  (0, 1, 7): 0,
    (0, 1, 8): 0,  (0, 1, 9): 1,  (0, 1, 10): 0,
    (0, 1, 11): 1,  (0, 1, 12): 1,  (0, 1, 13): 1,
    (0, 1, 14): 1,  (0, 1, 15): 0,  (0, 1, 16): 1,
    (0, 1, 17): 1,  (0, 1, 18): 1,  (0, 1, 20): 0,
    (0, 1, 21): 1,  (0, 1, 22): 1,  (0, 1, 23): 0,
    (0, 1, 24): 0,  (0, 1, 25): 1,  (0, 1, 26): 1,
    (0, 1, 28): 1,  (0, 1, 29): 0,  (0, 1, 30): 1,
    (0, 1, 31): 1,  (0, 1, 32): 0,  (0, 1, 33): 0,
    (0, 1, 34): 0,  (0, 1, 35): 0,  (0, 1, 36): 0,
    (0, 1, 37): 1,  (0, 1, 39): 1,  (0, 1, 40): 0,
    (0, 1, 41): 1,  (0, 1, 42): 1,  (0, 1, 43): 0,
    (0, 1, 45): 1,  (0, 1, 48): 0,  (0, 1, 49): 1,
    (0, 1, 50): 1,  (0, 1, 51): 1,  (0, 1, 52): 1,
    (0, 1, 55): 1,  (0, 1, 57): 1,  (0, 1, 58): 0,
    (0, 1, 59): 1,  (0, 1, 60): 0,  (0, 1, 61): 1,
    (0, 2, 4): 0,  (0, 2, 5): 0,  (0, 2, 6): 1,
    (0, 2, 7): 1,  (0, 2, 9): 1,  (0, 2, 11): 1,
    (0, 2, 13): 0,  (0, 2, 14): 1,  (0, 2, 15): 1,
    (0, 2, 16): 1,  (0, 2, 18): 0,  (0, 2, 20): 1,
    (0, 2, 22): 0,  (0, 2, 23): 1,  (0, 2, 24): 1,
    (0, 2, 27): 0,  (0, 2, 30): 1,  (0, 2, 31): 1,
    (0, 2, 32): 1,  (0, 2, 33): 1,  (0, 2, 35): 1,
    (0, 2, 36): 1,  (0, 2, 40): 0,  (0, 2, 41): 1,
    (0, 2, 42): 0,  (0, 2, 47): 1,  (0, 2, 50): 0,
    (0, 2, 51): 0,  (0, 2, 56): 0,  (0, 2, 58): 1,
    (0, 2, 59): 1,  (0, 2, 60): 1,  (0, 3, 6): 1,
    (0, 3, 7): 1,  (0, 3, 9): 1,  (0, 3, 12): 1,
    (0, 3, 15): 0,  (0, 3, 18): 0,  (0, 3, 21): 0,
    (0, 3, 24): 0,  (0, 3, 27): 0,  (0, 3, 30): 1,
    (0, 3, 31): 1,  (0, 3, 35): 1,  (0, 3, 39): 1,
    (0, 3, 45): 1,  (0, 3, 51): 0,  (0, 3, 59): 1,
    (0, 4, 9): 1,  (0, 4, 13): 0,  (0, 4, 18): 1,
    (0, 4, 22): 1,  (0, 4, 27): 1,  (0, 4, 31): 1,
    (0, 4, 32): 0,  (0, 4, 36): 0,  (0, 4, 49): 1,
    (0, 7, 14): 1,  (0, 7, 21): 1,  (0, 7, 28): 1,
    (0, 7, 35): 0,  (0, 7, 42): 1,  (0, 7, 49): 0,
    (0, 9, 18): 0,  (0, 9, 27): 1,  (0, 14, 28): 1,
    (0, 14, 35): 1,  (0, 14, 42): 0,  (0, 21, 42): 0,
}


def rebuild(n=N, subgroup=None, table=None):
    """Regenerate the colouring of all C(n,3) triples from TABLE alone."""
    subgroup = SUBGROUP if subgroup is None else subgroup
    table = TABLE if table is None else table
    chi = {}
    for rep, colour in table.items():
        stack = [rep]
        while stack:
            t = stack.pop()
            if t in chi:
                continue
            chi[t] = colour
            for u in subgroup:
                img = tuple(sorted((u * v) % n for v in t))
                if img not in chi:
                    stack.append(img)
            sh = tuple(sorted((v + 1) % n for v in t))
            if sh not in chi:
                stack.append(sh)
    return chi


def verify(chi=None, n=N):
    """Return (mono K_4 in colour 0, mono K_6 in colour 1)."""
    chi = rebuild() if chi is None else chi
    bad4 = 0
    for a in range(n):
        for b in range(a + 1, n):
            for c in range(b + 1, n):
                if chi[(a, b, c)]:
                    continue
                for d in range(c + 1, n):
                    if not (chi[(a, b, d)] or chi[(a, c, d)] or chi[(b, c, d)]):
                        bad4 += 1
    bad6 = 0
    for a in range(n):
        for b in range(a + 1, n):
            for c in range(b + 1, n):
                if not chi[(a, b, c)]:
                    continue
                for d in range(c + 1, n):
                    if not (chi[(a, b, d)] and chi[(a, c, d)] and chi[(b, c, d)]):
                        continue
                    for e in range(d + 1, n):
                        if not all(chi[t] for t in ((a, b, e), (a, c, e), (a, d, e),
                                                    (b, c, e), (b, d, e), (c, d, e))):
                            continue
                        for f in range(e + 1, n):
                            if all(chi[t] for t in (
                                    (a, b, f), (a, c, f), (a, d, f), (a, e, f),
                                    (b, c, f), (b, d, f), (b, e, f),
                                    (c, d, f), (c, e, f), (d, e, f))):
                                bad6 += 1
    return bad4, bad6


if __name__ == "__main__":
    from collections import Counter
    chi = rebuild()
    print(f"triples coloured: {len(chi)} (expected {N*(N-1)*(N-2)//6})")
    print("colour classes:", dict(sorted(Counter(chi.values()).items())))
    b4, b6 = verify(chi)
    print(f"mono K_4 in colour 0: {b4}    mono K_6 in colour 1: {b6}")
    ok = (b4 == 0 and b6 == 0)
    print("R(4,6;3) >=", N + 1 if ok else "FAILED")
    if not ok:
        print(f"FAILED: b4={b4} b6={b6}", file=sys.stderr)
        sys.exit(1)
