"""Compute |G| from generators, so the 5'-condition is a fact and not a claim.

WHY.  `groups.json` carries an `order` for each of its 45 groups, but those
numbers were *asserted* by the agents that constructed the groups -- derived
from the abstract structure ("S_4 wr AGL(3,2), so 24^8 * 1344"), not measured
from the permutations actually stored in the file.  Two of them are around
10^15 and cannot be checked by enumerating the group.

The number matters.  `obstruction.py` shows that if 5 divides |G| then no
G-invariant colouring can be a witness, so a search over that class is doomed
before it starts and its UNSAT says nothing.  An UNSAT is only informative when
the class was capable of containing a witness, and "|G| is prime to 5" is the
condition for that.  Trusting a description for it would be exactly the kind of
unverified claim that this project's rules exist to prevent.

Schreier-Sims settles it in polynomial time: build a stabiliser chain, and |G|
is the product of the basic orbit lengths.  Degree 35 with a handful of
generators takes milliseconds, whatever |G| turns out to be.
"""

from __future__ import annotations

import json
from itertools import combinations


def _mul(p, q):
    """Permutation product: apply p, then q."""
    return tuple(q[p[i]] for i in range(len(p)))


def _inv(p):
    out = [0] * len(p)
    for i, v in enumerate(p):
        out[v] = i
    return tuple(out)


def stabiliser_chain(gens, n):
    """Sims' incremental Schreier-Sims.  Returns (base, transversals).

    Correctness rests on one condition: at every level i, every Schreier
    generator u_x * g * u_{x^g}^{-1} must sift to the identity.  The loop below
    checks exactly that, and on a failure adds the residue as a new strong
    generator and restarts the check from the deepest level.  Each such
    addition either lengthens the base or grows a basic orbit, both bounded, so
    it terminates.
    """
    ident = tuple(range(n))
    for g in gens:
        if len(g) != n or sorted(g) != list(range(n)):
            raise ValueError(f"generator is not a permutation of {n} points")

    base: list[int] = []
    sgs: list[tuple] = []

    def gens_fixing(i):
        return [g for g in sgs if all(g[b] == b for b in base[:i])]

    def transversal(i):
        b = base[i]
        gs = gens_fixing(i)
        u = {b: ident}
        stack = [b]
        while stack:
            x = stack.pop()
            for g in gs:
                y = g[x]
                if y not in u:
                    u[y] = _mul(u[x], g)
                    stack.append(y)
        return u

    def sift(g, trans):
        for i in range(len(base)):
            x = g[base[i]]
            if x not in trans[i]:
                return g, i
            g = _mul(g, _inv(trans[i][x]))
        return g, len(base)

    def add_strong(g):
        if all(g[b] == b for b in base):        # g fixes the whole base
            base.append(next(i for i in range(n) if g[i] != i))
        sgs.append(g)

    for g in gens:
        t = tuple(g)
        if t != ident:
            add_strong(t)
    if not base:
        return [], []

    trans = [transversal(i) for i in range(len(base))]
    i = len(base) - 1
    while i >= 0:
        restart = False
        for x, ux in list(trans[i].items()):
            for g in gens_fixing(i):
                sg = _mul(_mul(ux, g), _inv(trans[i][g[x]]))
                if sg == ident:
                    continue
                res, _ = sift(sg, trans)
                if res != ident:
                    add_strong(res)
                    trans = [transversal(j) for j in range(len(base))]
                    restart = True
                    break
            if restart:
                break
        if restart:
            i = len(base) - 1
        else:
            i -= 1
    return base, trans


def group_order(gens, n):
    """|G| for the group generated by `gens` on `n` points, computed not claimed."""
    _, trans = stabiliser_chain(gens, n)
    out = 1
    for u in trans:
        out *= len(u)
    return out


def contains(gens, n, perm):
    """Is `perm` an element of the group generated by `gens`?

    Membership by sifting through the stabiliser chain: strip perm level by
    level, and it lies in the group exactly when the residue is the identity.

    Used to check a precondition, not for its own sake. `build_cnf` walks all
    C(n,s) subsets to collect the distinct orbit-sets, which is 39 million sets
    for R(5,5;3) at n=88. If the group contains every translation x -> x+c, then
    every subset can be translated to one containing the point 0, so walking
    only the subsets that contain 0 -- C(n-1,s-1) of them, a factor of n/s fewer
    -- reaches every orbit and therefore collects exactly the same clauses. The
    shortcut is sound ONLY under that precondition, so it has to be tested
    rather than assumed.
    """
    ident = tuple(range(n))
    perm = tuple(perm)
    if len(perm) != n or sorted(perm) != list(range(n)):
        raise ValueError(f"not a permutation of {n} points")
    if perm == ident:
        return True
    base, trans = stabiliser_chain(gens, n)
    g = perm
    for i, b in enumerate(base):
        x = g[b]
        if x not in trans[i]:
            return False
        g = _mul(g, _inv(trans[i][x]))
    return g == ident


def has_all_translations(gens, n):
    """True when x -> x+1 mod n is in the group (hence every translation)."""
    return contains(gens, n, [(i + 1) % n for i in range(n)])


def audit(groups, n=35):
    """Check every claimed order and 5'-status.  Returns a list of findings."""
    out = []
    for g in groups:
        computed = group_order(g["generators"], n)
        claimed = g.get("order")
        out.append({
            "name": g["name"],
            "claimed_order": claimed,
            "computed_order": computed,
            "order_matches": claimed == computed,
            "is_5prime": computed % 5 != 0,
            "vars": g.get("orbit_count_4subsets"),
        })
    return out


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--groups", default="groups.json")
    ap.add_argument("--n", type=int, default=35)
    ap.add_argument("--out", default="group_audit.json")
    a = ap.parse_args()

    with open(a.groups) as f:
        groups = json.load(f)
    rows = audit(groups, a.n)
    bad = [r for r in rows if not r["order_matches"]]
    not5 = [r for r in rows if not r["is_5prime"]]

    for r in sorted(rows, key=lambda r: r["vars"] or 0):
        flag = "" if r["order_matches"] else "  <-- CLAIMED ORDER IS WRONG"
        five = "" if r["is_5prime"] else "  <-- 5 DIVIDES |G|: CLASS IS DOOMED"
        print(f'{r["vars"]:>6} vars  |G|={r["computed_order"]:<18} '
              f'{r["name"]}{flag}{five}')
    with open(a.out, "w") as f:
        json.dump(rows, f, indent=1)
    print(f"\n{len(rows)} groups: {len(bad)} order mismatch, "
          f"{len(not5)} with 5 | |G| (their UNSAT would be predetermined)")

    # This program exists to find these two conditions. Printing them and
    # exiting 0 makes it a report, not an audit, and a caller that reads the
    # exit status -- which is the only thing a shell reads -- sees success.
    if bad or not5:
        import sys
        print(f"\nFAILED: {len(bad)} order mismatch, {len(not5)} with 5 | |G|",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
