"""The 5'-group obstruction: which symmetry ansaetze can hold a witness.

THE LEMMA.  Let chi be a 2-colouring of the 4-subsets of an n-set with no
monochromatic K5^(4) (a "witness").  Then no colour-preserving automorphism of
chi has a 5-cycle; equivalently, Aut(chi) is a 5'-group (5 does not divide its
order).

Proof.  Suppose g in Aut(chi) has a 5-cycle (a0 a1 a2 a3 a4).  Put S = {a0..a4}.
The subgroup <g> permutes the five 4-subsets S\\{a_i} transitively, because g
shifts the omitted index by one.  chi is constant on <g>-orbits, so all five
faces of S carry one colour: S is a monochromatic K5^(4).  Contradiction.

For the converse direction of the "5'-group" phrasing: a permutation with a
5-cycle has order divisible by 5, and conversely if 5 | |G| then Cauchy supplies
an element of order 5, whose cycle type consists of 1-cycles and 5-cycles and
which, being non-identity, has at least one 5-cycle.  So

    some element of G has a 5-cycle   <==>   5 divides |G|.

There is no cycle-type analysis to do: check the group order.  (An element of
order 10 whose cycle type is all 10-cycles has no 5-cycle itself, but its square
does, and 5 | |G| regardless.)

COROLLARIES.

1.  Z_n-invariant (cyclic) search is empty whenever 5 | n: translation by n/5
    5-cycles the arithmetic progression {0, n/5, 2n/5, 3n/5, 4n/5}.  This
    retro-explains the n=20 and n=30 nulls and, decisively, EXCLUDES n=35 --
    the target.

2.  No witness on 35 points has a vertex-transitive automorphism group: such a
    group has order divisible by 35 by orbit-stabiliser, hence by 5.

3.  Every point-orbit of an admissible group has size coprime to 5.

NOT A NOVELTY CLAIM.  This is the k = s-1 "simplex" case, where
the facets of K_s^(s-1) biject with its vertices, so any group transitive on the
s vertices is transitive on the s facets.  It is the hypergraph analogue of the
classical fact that a circulant 2-colouring of Z_n with 3 | n contains the
monochromatic triangle {0, n/3, 2n/3}.  Folklore; recorded here because it
reroutes this row's search, not because it is new mathematics.

Run:  python3 obstruction.py
"""

from __future__ import annotations

from itertools import combinations
from math import comb, gcd

# --------------------------------------------------------------------------
# Group actions on a point set, described by generators as permutations.
# --------------------------------------------------------------------------


def close_group(gens, points):
    """The permutation group generated by `gens`, as a set of tuples.

    Each generator is a dict or a callable point -> point.  Returns a list of
    permutations, each a tuple indexed by position in `points`.
    """
    index = {p: i for i, p in enumerate(points)}
    ident = tuple(range(len(points)))

    def as_tuple(g):
        f = g.__getitem__ if isinstance(g, dict) else g
        return tuple(index[f(p)] for p in points)

    frontier = [ident]
    seen = {ident}
    gen_tuples = [as_tuple(g) for g in gens]
    while frontier:
        nxt = []
        for h in frontier:
            for g in gen_tuples:
                composed = tuple(g[h[i]] for i in range(len(points)))
                if composed not in seen:
                    seen.add(composed)
                    nxt.append(composed)
        frontier = nxt
    return sorted(seen)


def cycle_lengths(perm):
    """Multiset of cycle lengths of a permutation given as a tuple."""
    n = len(perm)
    unseen = set(range(n))
    out = []
    while unseen:
        start = unseen.pop()
        length = 1
        cur = perm[start]
        while cur != start:
            unseen.discard(cur)
            cur = perm[cur]
            length += 1
        out.append(length)
    return sorted(out)


def has_five_cycle(perm):
    return 5 in cycle_lengths(perm)


# --------------------------------------------------------------------------
# The obstruction itself.
# --------------------------------------------------------------------------


def orbits_of_faces(group, points, k=4):
    """Partition the k-subsets of `points` into orbits under `group`.

    Returns {canonical representative -> orbit size}.
    """
    index = {p: i for i, p in enumerate(points)}
    rep_of = {}
    sizes = {}
    for face in combinations(range(len(points)), k):
        if face in rep_of:
            continue
        orbit = set()
        for g in group:
            orbit.add(tuple(sorted(g[i] for i in face)))
        rep = min(orbit)
        for f in orbit:
            rep_of[f] = rep
        sizes[rep] = len(orbit)
    return rep_of, sizes


def forced_monochromatic(group, points, s=5, k=4):
    """s-subsets whose k-faces all lie in ONE orbit -- forced monochromatic.

    Any invariant colouring makes each of these an s-clique, so a group with a
    nonempty return value admits no invariant witness at all.
    """
    rep_of, _ = orbits_of_faces(group, points, k)
    bad = []
    for W in combinations(range(len(points)), s):
        reps = {rep_of[f] for f in combinations(W, k)}
        if len(reps) == 1:
            bad.append(W)
    return bad


def cyclic_obstruction(n):
    """The explicit witness to Corollary 1: the 5-term AP, when 5 | n.

    Returns (S, faces, n_orbits) with n_orbits == 1 exactly when 5 | n.
    """
    if n % 5:
        return None
    step = n // 5
    S = [(i * step) % n for i in range(5)]
    faces = [tuple(sorted(x for x in S if x != drop)) for drop in S]

    def rep(face):
        return min(tuple(sorted((v + sh) % n for v in face)) for sh in range(n))

    return S, faces, len({rep(f) for f in faces})


def admissible(group_order):
    """The whole test: a group can hold a witness iff its order is a 5'-number."""
    return group_order % 5 != 0


# --------------------------------------------------------------------------
# Candidate ansaetze on 35 points, for the search ladder.
# --------------------------------------------------------------------------


def blocks_c7():
    """C_7 acting within five disjoint 7-blocks: (b, x) -> (b, x + 1)."""
    points = [(b, x) for b in range(5) for x in range(7)]
    gen = {(b, x): (b, (x + 1) % 7) for (b, x) in points}
    return points, [gen]


def cyclic_plus_fixed(base, extra):
    """Z_base acting on `base` points, with `extra` further points fixed.

    This is the family that contains the ansatz that actually works: the base
    can be warm-started from a known Z_base witness.  |G| = base, so the group
    is admissible whenever 5 does not divide `base`.
    """
    points = [("z", i) for i in range(base)] + [("f", j) for j in range(extra)]
    gen = {}
    for i in range(base):
        gen[("z", i)] = ("z", (i + 1) % base)
    for j in range(extra):
        gen[("f", j)] = ("f", j)
    return points, [gen]


def full_cyclic(n):
    """Z_n acting on n points -- the ansatz this module retires for 5 | n."""
    points = list(range(n))
    return points, [{i: (i + 1) % n for i in range(n)}]


def link_orbit_count(base):
    """Orbit variables contributed by one added point over a Z_base core.

    Adding a point oo to a base B means colouring the 3-subsets of B (the link
    of oo).  Under translation, a 3-subset has a nontrivial stabiliser exactly
    when 3 | base and it is {x, x + base/3, x + 2*base/3}.
    """
    total = comb(base, 3)
    if base % 3 == 0:
        short = base // 3          # that many such 3-subsets, forming ONE orbit
        return (total - short) // base + 1
    return total // base


def extension_variables(base, extra):
    """Orbit variables in the Z_base + `extra` fixed points ansatz, by stratum.

    Strata are indexed by how many of the added points a 4-subset contains.
    Faces inside the base are the core; the rest are what a warm start leaves
    free.
    """
    core = _orbit_count_of_subsets(base, 4)
    strata = {0: core}
    for j in range(1, min(extra, 4) + 1):
        # choose j added points, and 4-j base points, up to translation
        strata[j] = comb(extra, j) * _orbit_count_of_subsets(base, 4 - j)
    return strata


def _orbit_count_of_subsets(n, k):
    """Number of Z_n-translation orbits of k-subsets of Z_n (Burnside)."""
    if k == 0:
        return 1
    if k > n:
        return 0
    total = 0
    for d in range(n):
        g = gcd(d, n)               # translation by d has order n/g... use fixed sets
        # A k-subset fixed by +d is a union of cosets of <d>, which has size n/g.
        period = n // g
        if k % period == 0:
            total += comb(g, k // period)
    return total // n


# --------------------------------------------------------------------------


def _report():
    print("=" * 74)
    print("COROLLARY 1 -- cyclic search is empty whenever 5 | n")
    print("=" * 74)
    for n in (5, 10, 15, 20, 25, 30, 31, 32, 33, 34, 35):
        got = cyclic_obstruction(n)
        if got is None:
            print(f"  n={n:>3}: 5 does not divide n -- lemma is SILENT here")
            continue
        S, _faces, n_orb = got
        assert n_orb == 1, (n, n_orb)
        print(f"  n={n:>3}: S={S} -> 5 faces in {n_orb} orbit  ==> NO CYCLIC WITNESS")
    print()
    print("  Note n=34 is NOT excluded: the unresolved 46-minute run has no")
    print("  structural explanation.  It was simply hard.")
    print()

    print("=" * 74)
    print("NEGATIVE CONTROLS -- groups the lemma forbids really do force a clique")
    print("=" * 74)
    for label, (points, gens) in (
        ("Z_35 (full cyclic)", full_cyclic(35)),
        ("Z_20 (full cyclic)", full_cyclic(20)),
        ("Z_30 (full cyclic)", full_cyclic(30)),
    ):
        group = close_group(gens, points)
        order = len(group)
        five = sum(1 for g in group if has_five_cycle(g))
        bad = forced_monochromatic(group, points)
        print(f"  {label:<22} |G|={order:>5}  5||G|={not admissible(order)!s:<5} "
              f"elts with 5-cycle={five:<5} forced-mono 5-sets={len(bad)}")
        assert not admissible(order) and five > 0 and bad, label
    print()

    print("=" * 74)
    print("POSITIVE CONTROLS -- admissible groups force nothing")
    print("=" * 74)
    cands = [("block-C_7 on 5x7", blocks_c7())]
    for base, extra in ((33, 2), (32, 3), (31, 4), (34, 1)):
        cands.append((f"Z_{base} + {extra} fixed", cyclic_plus_fixed(base, extra)))
    for label, (points, gens) in cands:
        group = close_group(gens, points)
        order = len(group)
        five = sum(1 for g in group if has_five_cycle(g))
        _, sizes = orbits_of_faces(group, points)
        n_vars = len(sizes)
        bad = forced_monochromatic(group, points)
        print(f"  {label:<22} |G|={order:>5}  admissible={admissible(order)!s:<5} "
              f"elts with 5-cycle={five:<3} orbit vars={n_vars:>5} "
              f"forced-mono={len(bad)}")
        assert admissible(order) and five == 0 and not bad, label
    print()

    print("=" * 74)
    print("THE LADDER -- warm-startable extensions of witnesses already held")
    print("=" * 74)
    print(f"  {'ansatz':<20} {'|G|':>4} {'core':>7} {'free':>7} {'total':>7}  base status")
    known = {31: "SAT (9.3s)", 32: "SAT (5.3s)", 33: "SAT (100.7s)", 34: "UNRESOLVED"}
    for base, extra in ((33, 1), (33, 2), (32, 3), (31, 4), (34, 1)):
        if base + extra not in (34, 35):
            continue
        strata = extension_variables(base, extra)
        core = strata[0]
        free = sum(v for j, v in strata.items() if j)
        print(f"  Z_{base} + {extra} fixed{'':<7} {base:>4} {core:>7} {free:>7} "
              f"{core + free:>7}  n={base}: {known.get(base, '?')}"
              f"   -> {base + extra} points")
    print()
    print("  'free' is what remains once the base is pinned to a known witness.")
    print("  Z_33 + 1 -> a 34-point object: the order DS1 records only as the")
    print("  unpublished [Ex24] personal communication.")


if __name__ == "__main__":
    _report()
